# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_explorer.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_files_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_files_3.setGeometry(QtCore.QRect(10, 20, 451, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_files_3.setFont(font)
        self.groupBox_files_3.setFlat(False)
        self.groupBox_files_3.setObjectName("groupBox_files_3")
        self.comboBox_fileformat = QtWidgets.QComboBox(self.groupBox_files_3)
        self.comboBox_fileformat.setGeometry(QtCore.QRect(10, 39, 141, 22))
        self.comboBox_fileformat.setEditable(True)
        self.comboBox_fileformat.setObjectName("comboBox_fileformat")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.groupBox_files_3)
        self.lineEdit_filename.setGeometry(QtCore.QRect(170, 40, 211, 20))
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.label_37 = QtWidgets.QLabel(self.groupBox_files_3)
        self.label_37.setGeometry(QtCore.QRect(10, 18, 61, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_files_3)
        self.label_38.setGeometry(QtCore.QRect(170, 20, 47, 13))
        self.label_38.setObjectName("label_38")
        self.pushButton_browsefile = QtWidgets.QPushButton(self.groupBox_files_3)
        self.pushButton_browsefile.setGeometry(QtCore.QRect(390, 40, 51, 21))
        self.pushButton_browsefile.setObjectName("pushButton_browsefile")
        self.groupBox_vis = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_vis.setGeometry(QtCore.QRect(10, 120, 731, 611))
        self.groupBox_vis.setObjectName("groupBox_vis")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 381, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.scatterlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.scatterlayout.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout.setObjectName("scatterlayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(480, 30, 241, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.zhistlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.zhistlayout.setContentsMargins(0, 0, 0, 0)
        self.zhistlayout.setObjectName("zhistlayout")
        self.radioButtonxz = QtWidgets.QRadioButton(self.groupBox_vis)
        self.radioButtonxz.setGeometry(QtCore.QRect(160, 330, 71, 17))
        self.radioButtonxz.setObjectName("radioButtonxz")
        self.pushButton_smallROI = QtWidgets.QPushButton(self.groupBox_vis)
        self.pushButton_smallROI.setGeometry(QtCore.QRect(140, 290, 111, 31))
        self.pushButton_smallROI.setObjectName("pushButton_smallROI")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 360, 381, 241))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.scatterlayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.scatterlayout_3.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_3.setObjectName("scatterlayout_3")
        self.radioButtonxy = QtWidgets.QRadioButton(self.groupBox_vis)
        self.radioButtonxy.setGeometry(QtCore.QRect(70, 330, 71, 17))
        self.radioButtonxy.setObjectName("radioButtonxy")
        self.radioButtonyz = QtWidgets.QRadioButton(self.groupBox_vis)
        self.radioButtonyz.setGeometry(QtCore.QRect(250, 330, 71, 17))
        self.radioButtonyz.setObjectName("radioButtonyz")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_vis)
        self.pushButton.setGeometry(QtCore.QRect(610, 302, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_zmin = QtWidgets.QLineEdit(self.groupBox_vis)
        self.lineEdit_zmin.setGeometry(QtCore.QRect(460, 310, 61, 20))
        self.lineEdit_zmin.setObjectName("lineEdit_zmin")
        self.lineEdit_zmax = QtWidgets.QLineEdit(self.groupBox_vis)
        self.lineEdit_zmax.setGeometry(QtCore.QRect(540, 310, 61, 20))
        self.lineEdit_zmax.setObjectName("lineEdit_zmax")
        self.label = QtWidgets.QLabel(self.groupBox_vis)
        self.label.setGeometry(QtCore.QRect(460, 290, 47, 13))
        self.label.setObjectName("label")
        self.label_zmax = QtWidgets.QLabel(self.groupBox_vis)
        self.label_zmax.setGeometry(QtCore.QRect(540, 290, 47, 13))
        self.label_zmax.setObjectName("label_zmax")
        self.pushButton_scatter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_scatter.setGeometry(QtCore.QRect(470, 50, 61, 31))
        self.pushButton_scatter.setObjectName("pushButton_scatter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MPS explorer"))
        self.groupBox_files_3.setTitle(_translate("MainWindow", "Load SMLM data "))
        self.comboBox_fileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.label_37.setText(_translate("MainWindow", "File format"))
        self.label_38.setText(_translate("MainWindow", "Filename"))
        self.pushButton_browsefile.setText(_translate("MainWindow", "Browse"))
        self.groupBox_vis.setTitle(_translate("MainWindow", "Visualization (output)"))
        self.radioButtonxz.setText(_translate("MainWindow", "Plot (x,z)"))
        self.pushButton_smallROI.setText(_translate("MainWindow", "Set Small ROI"))
        self.radioButtonxy.setText(_translate("MainWindow", "Plot (x,y)"))
        self.radioButtonyz.setText(_translate("MainWindow", "Plot (y,z)"))
        self.pushButton.setText(_translate("MainWindow", "select Z range"))
        self.label.setText(_translate("MainWindow", "Z min"))
        self.label_zmax.setText(_translate("MainWindow", "Z max"))
        self.pushButton_scatter.setText(_translate("MainWindow", "Scatter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

