# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_explorer.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1548, 903)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_files_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_files_3.setGeometry(QtCore.QRect(20, 10, 451, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_files_3.setFont(font)
        self.groupBox_files_3.setFlat(False)
        self.groupBox_files_3.setObjectName("groupBox_files_3")
        self.comboBox_fileformat = QtWidgets.QComboBox(self.groupBox_files_3)
        self.comboBox_fileformat.setGeometry(QtCore.QRect(10, 39, 141, 22))
        self.comboBox_fileformat.setEditable(True)
        self.comboBox_fileformat.setObjectName("comboBox_fileformat")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.groupBox_files_3)
        self.lineEdit_filename.setGeometry(QtCore.QRect(170, 40, 211, 20))
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.label_37 = QtWidgets.QLabel(self.groupBox_files_3)
        self.label_37.setGeometry(QtCore.QRect(10, 18, 81, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_files_3)
        self.label_38.setGeometry(QtCore.QRect(170, 20, 71, 16))
        self.label_38.setObjectName("label_38")
        self.pushButton_browsefile = QtWidgets.QPushButton(self.groupBox_files_3)
        self.pushButton_browsefile.setGeometry(QtCore.QRect(390, 40, 51, 21))
        self.pushButton_browsefile.setObjectName("pushButton_browsefile")
        self.pushButton_browsefile_2 = QtWidgets.QPushButton(self.groupBox_files_3)
        self.pushButton_browsefile_2.setGeometry(QtCore.QRect(390, 90, 51, 21))
        self.pushButton_browsefile_2.setObjectName("pushButton_browsefile_2")
        self.label_39 = QtWidgets.QLabel(self.groupBox_files_3)
        self.label_39.setGeometry(QtCore.QRect(10, 68, 81, 16))
        self.label_39.setObjectName("label_39")
        self.comboBox_fileformat_2 = QtWidgets.QComboBox(self.groupBox_files_3)
        self.comboBox_fileformat_2.setGeometry(QtCore.QRect(10, 89, 141, 22))
        self.comboBox_fileformat_2.setEditable(True)
        self.comboBox_fileformat_2.setObjectName("comboBox_fileformat_2")
        self.lineEdit_filename_2 = QtWidgets.QLineEdit(self.groupBox_files_3)
        self.lineEdit_filename_2.setGeometry(QtCore.QRect(170, 90, 211, 20))
        self.lineEdit_filename_2.setObjectName("lineEdit_filename_2")
        self.label_40 = QtWidgets.QLabel(self.groupBox_files_3)
        self.label_40.setGeometry(QtCore.QRect(170, 70, 71, 16))
        self.label_40.setObjectName("label_40")
        self.groupBox_vis = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_vis.setGeometry(QtCore.QRect(20, 150, 711, 681))
        self.groupBox_vis.setObjectName("groupBox_vis")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 381, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.scatterlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.scatterlayout.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout.setObjectName("scatterlayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(440, 20, 251, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.zhistlayoutch1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.zhistlayoutch1.setContentsMargins(0, 0, 0, 0)
        self.zhistlayoutch1.setObjectName("zhistlayoutch1")
        self.radioButtonxz = QtWidgets.QRadioButton(self.groupBox_vis)
        self.radioButtonxz.setGeometry(QtCore.QRect(160, 380, 71, 17))
        self.radioButtonxz.setObjectName("radioButtonxz")
        self.pushButton_smallROI = QtWidgets.QPushButton(self.groupBox_vis)
        self.pushButton_smallROI.setGeometry(QtCore.QRect(140, 340, 111, 31))
        self.pushButton_smallROI.setObjectName("pushButton_smallROI")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 410, 381, 251))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.scatterlayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.scatterlayout_3.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_3.setObjectName("scatterlayout_3")
        self.radioButtonxy = QtWidgets.QRadioButton(self.groupBox_vis)
        self.radioButtonxy.setGeometry(QtCore.QRect(70, 380, 71, 17))
        self.radioButtonxy.setObjectName("radioButtonxy")
        self.radioButtonyz = QtWidgets.QRadioButton(self.groupBox_vis)
        self.radioButtonyz.setGeometry(QtCore.QRect(250, 380, 71, 17))
        self.radioButtonyz.setObjectName("radioButtonyz")
        self.pushButton_zrange = QtWidgets.QPushButton(self.groupBox_vis)
        self.pushButton_zrange.setGeometry(QtCore.QRect(600, 360, 81, 31))
        self.pushButton_zrange.setObjectName("pushButton_zrange")
        self.lineEdit_zmin = QtWidgets.QLineEdit(self.groupBox_vis)
        self.lineEdit_zmin.setGeometry(QtCore.QRect(450, 370, 61, 20))
        self.lineEdit_zmin.setClearButtonEnabled(False)
        self.lineEdit_zmin.setObjectName("lineEdit_zmin")
        self.lineEdit_zmax = QtWidgets.QLineEdit(self.groupBox_vis)
        self.lineEdit_zmax.setGeometry(QtCore.QRect(530, 370, 61, 20))
        self.lineEdit_zmax.setObjectName("lineEdit_zmax")
        self.label = QtWidgets.QLabel(self.groupBox_vis)
        self.label.setGeometry(QtCore.QRect(460, 350, 47, 13))
        self.label.setObjectName("label")
        self.label_zmax = QtWidgets.QLabel(self.groupBox_vis)
        self.label_zmax.setGeometry(QtCore.QRect(540, 350, 47, 13))
        self.label_zmax.setObjectName("label_zmax")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(440, 410, 241, 221))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.zhistlayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.zhistlayout_2.setContentsMargins(0, 0, 0, 0)
        self.zhistlayout_2.setObjectName("zhistlayout_2")
        self.pushButton_savexyzROI = QtWidgets.QPushButton(self.groupBox_vis)
        self.pushButton_savexyzROI.setGeometry(QtCore.QRect(450, 640, 101, 31))
        self.pushButton_savexyzROI.setObjectName("pushButton_savexyzROI")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(440, 180, 251, 151))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.zhistlayoutch2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.zhistlayoutch2.setContentsMargins(0, 0, 0, 0)
        self.zhistlayoutch2.setObjectName("zhistlayoutch2")
        self.pushButton_savexyzROI_2 = QtWidgets.QPushButton(self.groupBox_vis)
        self.pushButton_savexyzROI_2.setGeometry(QtCore.QRect(570, 640, 101, 31))
        self.pushButton_savexyzROI_2.setObjectName("pushButton_savexyzROI_2")
        self.pushButton_scatter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_scatter.setGeometry(QtCore.QRect(500, 50, 61, 31))
        self.pushButton_scatter.setObjectName("pushButton_scatter")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(740, 130, 761, 701))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 90, 381, 241))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.scatterlayout_dbscan = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.scatterlayout_dbscan.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_dbscan.setObjectName("scatterlayout_dbscan")
        self.lineEdit_minsamples = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_minsamples.setGeometry(QtCore.QRect(20, 50, 61, 20))
        self.lineEdit_minsamples.setClearButtonEnabled(False)
        self.lineEdit_minsamples.setObjectName("lineEdit_minsamples")
        self.pushButton_DBSCAN = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_DBSCAN.setGeometry(QtCore.QRect(140, 40, 81, 31))
        self.pushButton_DBSCAN.setObjectName("pushButton_DBSCAN")
        self.label_minsamples = QtWidgets.QLabel(self.groupBox)
        self.label_minsamples.setGeometry(QtCore.QRect(20, 30, 111, 16))
        self.label_minsamples.setObjectName("label_minsamples")
        self.lineEdit_Nneighbor = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Nneighbor.setGeometry(QtCore.QRect(30, 390, 61, 20))
        self.lineEdit_Nneighbor.setClearButtonEnabled(False)
        self.lineEdit_Nneighbor.setObjectName("lineEdit_Nneighbor")
        self.label_eps_2 = QtWidgets.QLabel(self.groupBox)
        self.label_eps_2.setGeometry(QtCore.QRect(30, 370, 61, 16))
        self.label_eps_2.setObjectName("label_eps_2")
        self.pushButton_Distances = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Distances.setGeometry(QtCore.QRect(120, 380, 81, 31))
        self.pushButton_Distances.setObjectName("pushButton_Distances")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(410, 90, 331, 241))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.scatterlayout_histcmdist = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.scatterlayout_histcmdist.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_histcmdist.setObjectName("scatterlayout_histcmdist")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(420, 460, 301, 221))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.zhistlayout_cmdist = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.zhistlayout_cmdist.setContentsMargins(0, 0, 0, 0)
        self.zhistlayout_cmdist.setObjectName("zhistlayout_cmdist")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setGeometry(QtCore.QRect(420, 380, 181, 71))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_latmin = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_latmin.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.lineEdit_latmin.setObjectName("lineEdit_latmin")
        self.lineEdit_latmax = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_latmax.setGeometry(QtCore.QRect(60, 40, 41, 20))
        self.lineEdit_latmax.setObjectName("lineEdit_latmax")
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setGeometry(QtCore.QRect(130, 20, 81, 16))
        self.label_26.setObjectName("label_26")
        self.lineEdit_bin = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_bin.setGeometry(QtCore.QRect(130, 40, 41, 20))
        self.lineEdit_bin.setObjectName("lineEdit_bin")
        self.pushButton_remove_bad_cluster = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_remove_bad_cluster.setGeometry(QtCore.QRect(410, 40, 101, 31))
        self.pushButton_remove_bad_cluster.setObjectName("pushButton_remove_bad_cluster")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 440, 331, 241))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.scatterlayout_goodclus = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.scatterlayout_goodclus.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_goodclus.setObjectName("scatterlayout_goodclus")
        self.pushButton_savedistdata = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_savedistdata.setGeometry(QtCore.QRect(220, 380, 101, 31))
        self.pushButton_savedistdata.setObjectName("pushButton_savedistdata")
        self.pushButton_savecluscenters = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_savecluscenters.setGeometry(QtCore.QRect(540, 40, 121, 31))
        self.pushButton_savecluscenters.setObjectName("pushButton_savecluscenters")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1548, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MPS explorer"))
        self.groupBox_files_3.setTitle(_translate("MainWindow", "Load SMLM data "))
        self.comboBox_fileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.label_37.setText(_translate("MainWindow", "File format Ch1"))
        self.label_38.setText(_translate("MainWindow", "Filename Ch1"))
        self.pushButton_browsefile.setText(_translate("MainWindow", "Browse"))
        self.pushButton_browsefile_2.setText(_translate("MainWindow", "Browse"))
        self.label_39.setText(_translate("MainWindow", "File format Ch2"))
        self.comboBox_fileformat_2.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.label_40.setText(_translate("MainWindow", "Filename Ch2"))
        self.groupBox_vis.setTitle(_translate("MainWindow", "Visualization (output)"))
        self.radioButtonxz.setText(_translate("MainWindow", "Plot (x,z)"))
        self.pushButton_smallROI.setText(_translate("MainWindow", "Set Small ROI"))
        self.radioButtonxy.setText(_translate("MainWindow", "Plot (x,y)"))
        self.radioButtonyz.setText(_translate("MainWindow", "Plot (y,z)"))
        self.pushButton_zrange.setText(_translate("MainWindow", "select Z range"))
        self.label.setText(_translate("MainWindow", "Z min"))
        self.label_zmax.setText(_translate("MainWindow", "Z max"))
        self.pushButton_savexyzROI.setText(_translate("MainWindow", "save ROI Ch1"))
        self.pushButton_savexyzROI_2.setText(_translate("MainWindow", "save ROI Ch2"))
        self.pushButton_scatter.setText(_translate("MainWindow", "Scatter"))
        self.groupBox.setTitle(_translate("MainWindow", "Clustering (HDBSCAN)"))
        self.lineEdit_minsamples.setText(_translate("MainWindow", "10"))
        self.pushButton_DBSCAN.setText(_translate("MainWindow", "cluster"))
        self.label_minsamples.setText(_translate("MainWindow", "Min points per cluster"))
        self.lineEdit_Nneighbor.setText(_translate("MainWindow", "1"))
        self.label_eps_2.setText(_translate("MainWindow", "N neighbor"))
        self.pushButton_Distances.setText(_translate("MainWindow", "Distances"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Histogram settings"))
        self.label_2.setText(_translate("MainWindow", "Lateral range"))
        self.label_26.setText(_translate("MainWindow", "Binning"))
        self.pushButton_remove_bad_cluster.setText(_translate("MainWindow", "remove bad cluster"))
        self.pushButton_savedistdata.setText(_translate("MainWindow", "save dist data"))
        self.pushButton_savecluscenters.setText(_translate("MainWindow", "save clusters centers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

